image: Previous Visual Studio 2017

platform:
- x64

environment:
  matrix:
    - nodejs_version: "6"

cache:
  - '%APPDATA%\npm-cache -> package.json' # Only load this from cache if package.json is unchanged
  - '%LOCALAPPDATA%\Yarn'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: IF "%nodejs_version%"=="6" npm install -g npm@6
  - npm --version
  - yarn --frozen-lockfile

test_script:
  - yarn test

build: off
